#ifndef VFD_IOCTL_HPP
#define VFD_IOCTL_HPP

#include <cstdint>
enum vfd_ioctl_cmd_e : uint64_t { VFD_RUN = 0u, VFD_OFF, VFD_CHANGE_DIR, VFD_SET_ACCELERATION_TIME, VFD_SET_DEACCELERATION_TIME, VFD_SET_FREQ, VFD_SET_FWD, VFD_SET_REV, VFD_SET_STOP_MODE };
enum vfd_stop_mode_e : uint16_t { VFD_STOP_MODE_DEACCELERATE = 0u, VFD_STOP_MODE_FREE, VFD_STOP_MODE_DC_BRAKE };

#endif /* MODBUS_IOCTL_HPP */
